### YamlMime:YamlDocument
documentType: LandingData
title: Azure Container Service et documentation Kubernetes
metadata:
  title: 'Azure Container Service avec documentation Kubernetes - Didacticiels, Référence sur l’API | Microsoft Docs'
  meta.description: 'Azure Container Service allows you to quickly deploy a production ready Kubernetes cluster. Learn how to use Azure Container Service in concert with Kubernetes with these quickstarts, tutorials, and samples.'
  description: 'Azure Container Service vous permet de déployer un cluster Kubernetes prêt pour la production. Découvrez comment faire avec ces guides de démarrage rapide, tutoriels et exemples.'
  services: container-service
  author: georgewallace
  manager: gwallace
  ms.service: container-service
  ms.topic: landing-page
  ms.date: 07-21-2017
  ms.author: gwallace
abstract:
  description: 'Azure Container Service vous permet de déployer rapidement un cluster Kubernetes prêt pour la production. Découvrez comment utiliser Azure Container Service conjointement avec Kubernetes à l’aide ces démarrages rapides, de ces didacticiels et de ces exemples.'
sections:
  - title: "Démarrages en 5\_minutes"
    items:
      - type: paragraph
        text: "Découvrez comment déployer des clusters Kubernetes à l’aide d’Azure Container Service\_:"
      - type: list
        style: icon48
        items:
          - image:
              src: 'https://docs.microsoft.com/media/logos/logo_linux.svg'
            text: Créer un cluster Kubernetes
            href: /azure/container-service/kubernetes/container-service-kubernetes-walkthrough
  - title: Didacticiels pas à pas
    items:
      - type: paragraph
        text: 'Découvrez comment déployer, gérer et mettre à jour des applications dans un cluster Azure Container Service Kubernetes.'
      - type: list
        style: ordered
        items:
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-prepare-app">Créer des images de conteneur à partir d’une application</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-prepare-acr">Télécharger des images conteneur dans Azure Container Registry</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-deploy-cluster">Déployer un cluster Kubernetes dans in Azure Container Service</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-deploy-application">Exécuter vos images conteneur dans Kubernetes</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-scale">Mettre à l’échelle une application et l’infrastructure Kubernetes</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-app-update">Mettre à jour une application en cours d’exécution dans Kubernetes</a>
          - html: <a href="/azure/container-service/kubernetes/container-service-tutorial-kubernetes-monitor">Effectuer le monitoring de Kubernetes avec Log Analytics</a>
  - title: Exemples
    items:
      - type: list
        style: unordered
        className: spaced noBullet
        items:
          - html: <a href="/azure/container-service/cli-samples">Azure CLI</a>
  - title: Informations de référence
    items:
      - type: list
        style: cards
        className: cardsD
        items:
          - title: Ligne de commande
            html: <p><a href="/cli/azure/acs">Azure CLI</a></p>
          - title: REST
            html: <p><a href="/rest/api/container-service">REST API</a></p>