### YamlMime:Landing
title: Kubernetes avec Azure Arc
summary: Azure Arc étend les fonctionnalités d’Azure Resource Manager aux clusters Kubernetes sur toutes les infrastructures, qu’elles soient locales, multicloud et de périphérie.
metadata:
  title: Kubernetes avec Azure Arc
  description: Découvrir comment gérer les clusters Kubernetes
  author: mlearned
  manager: carmonm
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 05/19/2020
  ms.author: mlearned
  ms.openlocfilehash: a2ba3c789d6f7b6dea352468c01533b21c56812d
  ms.sourcegitcommit: fdec8e8bdbddcce5b7a0c4ffc6842154220c8b90
  ms.translationtype: HT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 05/19/2020
  ms.locfileid: "83661973"
landingContent:
- title: Vue d’ensemble d’Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: En savoir plus sur Azure Arc
      url: https://azure.microsoft.com/services/azure-arc/
- title: Connecter des clusters Kubernetes à Azure à l’aide d’Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: Qu’est-ce que Kubernetes avec Azure Arc ?
      url: ./overview.md
  - linkListType: how-to-guide
    links:
    - text: Connecter un cluster
      url: ./connect-cluster.md
    - text: Utiliser GitOps dans un cluster connecté
      url: ./use-gitops-connected-cluster.md
    - text: Utiliser GitOps avec Helm
      url: ./use-gitops-with-helm.md
    - text: Utiliser Azure Monitor pour conteneurs
      url: ./deploy-azure-monitor-for-containers.md
    - text: Utiliser Azure Policy
      url: ./use-azure-policy.md
    - text: Déployer des charges de travail Azure IoT Edge
      url: ./deploy-azure-iot-edge-workloads.md
    - text: Intégration d’un principal de service
      url: ./create-onboarding-service-principal.md
